# 📘 NumPy Daily Task – Indexing, Slicing, Fancy Indexing, Boolean Indexing, View & Copy


## Q1. Normal Indexing on a 1D Array

Input

a = np.array([10,20,30,40,50,60])

Tasks

1) Print the first element.
2) Print the third element.
3) Print the last element using negative indexing.
4) Print the second-last element.

Expected Output

10

30

60

50

Write your understanding in comments.


In [2]:
import numpy as np

# Input array
a = np.array([10, 20, 30, 40, 50, 60])

# Tasks
print(a[0])   # First element -> 10
print(a[2])   # Third element -> 30
print(a[-1])  # Last element using negative indexing -> 60
print(a[-2])  # Second-last element -> 50

# UNDERSTANDING:
# 1. NumPy arrays are 0-indexed, meaning the first element is at index 0.
# 2. Positive indices traverse left-to-right (0, 1, 2, ...).
# 3. Negative indices traverse right-to-left, starting at -1 for the last element.

10
30
60
50


## Q2. Normal Slicing on a 1D Array

Input

a = np.array([10,20,30,40,50,60,70,80])

Tasks

Print

- First four elements
- Last three elements
- Elements from index 2 to index 5
- Every second element
- Reverse the array

Write your understanding of

 start : stop : step


In [3]:
import numpy as np

# Input array
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])

# Tasks
print(a[:4])    # First four elements -> [10 20 30 40]
print(a[-3:])   # Last three elements -> [60 70 80]
print(a[2:6])   # Elements from index 2 to index 5 -> [30 40 50 60]
print(a[::2])   # Every second element -> [10 30 50 70]
print(a[::-1])  # Reverse the array -> [80 70 60 50 40 30 20 10]

# UNDERSTANDING OF start : stop : step:
# 1. 'start': Index where the slice begins (inclusive). Defaults to 0.
# 2. 'stop': Index where the slice ends (exclusive).
# 3. 'step': Step size/interval between items. Negative step reverses direction.

[10 20 30 40]
[60 70 80]
[30 40 50 60]
[10 30 50 70]
[80 70 60 50 40 30 20 10]


## Q3. Normal Indexing & Slicing on a 2D Array

Input
```
a = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
```
Tasks

Print

- First row
- Third column
- Element 60
- Last row
- First two rows
- Last two columns
- The sub-matrix

50 60

80 90

Write your understanding of row indexing, column indexing, and slicing.


In [4]:
import numpy as np

# Input array
a = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Tasks
print(a[0])       # First row -> [10 20 30]
print(a[:, 2])    # Third column -> [30 60 90]
print(a[1, 2])    # Element 60 -> 60
print(a[-1])      # Last row -> [70 80 90]
print(a[:2])      # First two rows -> [[10 20 30], [40 50 60]]
print(a[:, -2:])  # Last two columns -> [[20 30], [50 60], [80 90]]
print(a[1:, 1:])  # Sub-matrix 50 60 / 80 90 -> [[50 60], [80 90]]

# UNDERSTANDING:
# 1. 2D indexing syntax is: array[row_index_or_slice, column_index_or_slice].
# 2. Omitting column specification (e.g., a[0]) selects the full row.
# 3. A colon ':' on its own selects all items along that given axis.

[10 20 30]
[30 60 90]
60
[70 80 90]
[[10 20 30]
 [40 50 60]]
[[20 30]
 [50 60]
 [80 90]]
[[50 60]
 [80 90]]


## Q4. Normal Indexing & Slicing on a 3D Array

Input
```
a = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])
```

Tasks

Print

- Shape
- Number of dimensions
- First layer
- Second layer
- Element 8
- First row from both layers
- Second column from every layer

Explain how indexing changes from 2D to 3D.


In [5]:
import numpy as np

# Input array
a = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

# Tasks
print(a.shape)     # Shape -> (2, 2, 2)
print(a.ndim)      # Number of dimensions -> 3
print(a[0])        # First layer (layer 0)
print(a[1])        # Second layer (layer 1)
print(a[1, 1, 1])  # Element 8
print(a[:, 0, :])  # First row from both layers -> [[1 2], [5 6]]
print(a[:, :, 1])  # Second column from every layer -> [[2 4], [6 8]]

# UNDERSTANDING:
# 1. 3D array access follows array[layer/depth, row, column].
# 2. To index a single scalar, three integer coordinates are required.

(2, 2, 2)
3
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
8
[[1 2]
 [5 6]]
[[2 4]
 [6 8]]


## Q5. Fancy Indexing on a 1D Array

Input

a = np.array([10,20,30,40,50,60,70])

Tasks

Using Fancy Indexing only, print

- [10 30 50]
- [20 20 40]
- [70 50 30]

Explain what Fancy Indexing is.


In [6]:
import numpy as np

# Input array
a = np.array([10, 20, 30, 40, 50, 60, 70])

# Tasks
print(a[[0, 2, 4]])    # [10 30 50]
print(a[[1, 1, 3]])    # [20 20 40]
print(a[[-1, 4, 2]])   # [70 50 30]

# UNDERSTANDING:
# 1. Fancy indexing involves passing an integer array/list of indices to select arbitrary elements.
# 2. Unlike standard slicing (which creates views), fancy indexing always creates a new independent copy.

[10 30 50]
[20 20 40]
[70 50 30]


## Q6. Fancy Indexing on a 2D Array

Input
```
a = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
```

Tasks

Using Fancy Indexing only

Print

- First and third rows
- Elements 20 and 90
- Elements 40, 50, 60

Explain why Fancy Indexing is useful.


In [17]:
import numpy as np

# Input array
a = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Tasks using pure Fancy Indexing:
print(a[[0, 2]])                    # First and third rows -> [[10 20 30], [70 80 90]]
print(a[[0, 2], [1, 2]])            # Elements 20 and 90 -> [20 90]
print(a[[1, 1, 1], [0, 1, 2]])      # Elements 40, 50, 60 using pure coordinate pairs -> [40 50 60]

# UNDERSTANDING:
# 1. Pure fancy indexing pairs each index from row array with the corresponding index in column array (e.g., (1,0), (1,1), (1,2)).
# 2. It always returns a new copy rather than a view.

[[10 20 30]
 [70 80 90]]
[20 90]
[40 50 60]


## Q7. Boolean Indexing (1D)

Input

a = np.array([10,15,20,25,30,35,40,45,50])

Tasks

Print

- Values greater than 25
- Values less than 30
- Even numbers
- Odd numbers
- Values between 20 and 40

Explain Boolean Masking.


In [18]:
import numpy as np

# Input array
a = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50])

# Tasks
print(a[a > 25])                      # Values greater than 25 -> [30 35 40 45 50]
print(a[a < 30])                      # Values less than 30 -> [10 15 20 25]
print(a[a % 2 == 0])                  # Even numbers -> [10 20 30 40 50]
print(a[a % 2 != 0])                  # Odd numbers -> [15 25 35 45]
print(a[(a >= 20) & (a <= 40)])       # Values between 20 and 40 (inclusive) -> [20 25 30 35 40]

# UNDERSTANDING:
# 1. Relational operations on arrays create boolean masks containing True and False.
# 2. Combining multiple conditions requires bitwise operators (&, |) with parentheses.

[30 35 40 45 50]
[10 15 20 25]
[10 20 30 40 50]
[15 25 35 45]
[20 25 30 35 40]


## Q8. Boolean Indexing (2D)

Input
```
a = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
```
Tasks

Print

- Values greater than 50
- Values less than 40
- Even values only

Explain why Boolean Indexing returns a flattened array.


In [9]:
import numpy as np

# Input array
a = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Tasks
print(a[a > 50])        # Values greater than 50 -> [60 70 80 90]
print(a[a < 40])        # Values less than 40 -> [10 20 30]
print(a[a % 2 == 0])    # Even values only -> [10 20 30 40 50 60 70 80 90]

# UNDERSTANDING:
# 1. 2D boolean indexing returns a 1D flattened array.
# 2. Because the count of True conditions per row is typically non-uniform, NumPy flattens the output to preserve shape consistency.

[60 70 80 90]
[10 20 30]
[10 20 30 40 50 60 70 80 90]


## Q9. View Using Slicing

Input

a = np.array([10,20,30,40,50])

b = a[2:]

Tasks

Print

id(a)

id(b)

a.ctypes.data

b.ctypes.data

a.base

b.base

Now modify

b[0]=999

Print

a

b

Write your observations.


In [10]:
import numpy as np

# Input array
a = np.array([10, 20, 30, 40, 50])
b = a[2:]

# Tasks
print("id(a):", id(a))
print("id(b):", id(b))
print("a.ctypes.data:", a.ctypes.data)
print("b.ctypes.data:", b.ctypes.data)
print("a.base:", a.base)
print("b.base:", b.base)

# Modification
b[0] = 999
print("a after modification:", a)  # [ 10  20 999  40  50]
print("b after modification:", b)  # [999  40  50]

# OBSERVATIONS:
# 1. 'a' and 'b' have different id() because 'b' is a separate ndarray wrapper object.
# 2. 'b.base' points to 'a', showing that 'b' is a View sharing memory buffer with 'a'.
# 3. Modifying 'b[0]' directly alters 'a[2]'.

id(a): 137714277111952
id(b): 137714291760112
a.ctypes.data: 442016304
b.ctypes.data: 442016320
a.base: None
b.base: [10 20 30 40 50]
a after modification: [ 10  20 999  40  50]
b after modification: [999  40  50]


## Q10. View Using .view()

Input

a = np.array([10,20,30,40,50])

b = a.view()

Tasks

Repeat the same observations as Question 9.

Then explain

- Is .view() different from slicing?
- Why?


In [11]:
import numpy as np

# Input array
a = np.array([10, 20, 30, 40, 50])
b = a.view()

# Tasks
print("id(a):", id(a))
print("id(b):", id(b))
print("a.ctypes.data:", a.ctypes.data)
print("b.ctypes.data:", b.ctypes.data)
print("a.base:", a.base)
print("b.base:", b.base)

# Modification
b[0] = 888
print("a after modification:", a)  # [888  20  30  40  50]
print("b after modification:", b)  # [888  20  30  40  50]

# UNDERSTANDING:
# 1. Slicing creates a view with an offset memory address (points to the slice start).
# 2. .view() creates a view starting at the exact same memory address (same ctypes.data) and can be used to re-interpret data types.

id(a): 137714277112048
id(b): 137714277112144
a.ctypes.data: 443313584
b.ctypes.data: 443313584
a.base: None
b.base: [10 20 30 40 50]
a after modification: [888  20  30  40  50]
b after modification: [888  20  30  40  50]


## Q11. Copy Using .copy()

Input

a = np.array([10,20,30,40,50])

b = a.copy()

Tasks

Print

id()

ctypes.data

base

Modify

b[2]=999

Print

a

b

Write your observations.


In [12]:
import numpy as np

# Input array
a = np.array([10, 20, 30, 40, 50])
b = a.copy()

# Tasks
print("id(a):", id(a))
print("id(b):", id(b))
print("a.ctypes.data:", a.ctypes.data)
print("b.ctypes.data:", b.ctypes.data)
print("a.base:", a.base)
print("b.base:", b.base)

# Modification
b[2] = 999
print("a after modification:", a)  # [10 20 30 40 50] (Unchanged)
print("b after modification:", b)  # [ 10  20 999  40  50]

# OBSERVATIONS:
# 1. 'b.base' is None, meaning 'b' owns its own independent memory allocation.
# 2. Mutating 'b' has zero effect on the original array 'a'.

id(a): 137714277111088
id(b): 137714277111184
a.ctypes.data: 442016304
b.ctypes.data: 461104048
a.base: None
b.base: None
a after modification: [10 20 30 40 50]
b after modification: [ 10  20 999  40  50]


## Q12. View vs Copy Investigation

Create

a = np.array([1,2,3,4,5])

b = a[1:]

c = a.view()

d = a.copy()

Print

id()

ctypes.data

base

Modify all three variables separately.

Observe

- Which changes affect a?
- Which do not?

Write your observations.


In [13]:
import numpy as np

# Inputs
a = np.array([1, 2, 3, 4, 5])
b = a[1:]    # Sliced View
c = a.view() # Explicit View
d = a.copy() # Deep Copy

# Inspection
print("ids:", id(a), id(b), id(c), id(d))
print("ctypes:", a.ctypes.data, b.ctypes.data, c.ctypes.data, d.ctypes.data)
print("bases:", a.base, b.base is not None, c.base is not None, d.base)

# Modifications
b[0] = 200  # Modifies a[1]
c[0] = 100  # Modifies a[0]
d[0] = 500  # Does NOT modify a

print("Final a:", a)  # [100 200   3   4   5]
print("Final d:", d)  # [500   2   3   4   5]

# OBSERVATIONS:
# 1. Modifications to 'b' and 'c' alter 'a' because they share the underlying memory buffer.
# 2. Modifications to 'd' do not affect 'a' because .copy() uses a separate memory buffer.

ids: 137714277111664 137714277111088 137714277111184 137714277111568
ctypes: 443313584 443313592 443313584 461104048
bases: None True True None
Final a: [100 200   3   4   5]
Final d: [500   2   3   4   5]


## Q13. Prediction Question

Without executing the code first, predict the output.

a = np.array([1,2,3,4])

b = a[1:]

b[1]=100

print(a)

print(b)

After writing your prediction, execute the code and compare your answer.

Write what you learned.


In [14]:
import numpy as np

# PREDICTION:
# Slicing creates a view. 'b' starts at index 1 of 'a' ([2, 3, 4]).
# b[1] corresponds to index 2 of 'a' (the element 3).
# Setting b[1] = 100 will change 'a' to [1, 2, 100, 4] and 'b' to [2, 100, 4].

# Execution
a = np.array([1, 2, 3, 4])
b = a[1:]
b[1] = 100

print("a:", a)  # [  1   2 100   4]
print("b:", b)  # [  2 100   4]

# WHAT WE LEARNED:
# Slicing does not duplicate data; it mutates the parent array directly upon assignment.

a: [  1   2 100   4]
b: [  2 100   4]


## Q14. Memory Investigation

Using any View and Copy examples from this task, answer the following:

1) Why are id(a) and id(b) different?
2) Why can ctypes.data be different even though memory is shared?
3) Why is a.base equal to None?
4) Why does b.base point to a?
5) Which object owns the memory?

Write your explanation in comments.


In [15]:
# EXPLANATION OF MEMORY CONCEPTS:
# 1. Why id(a) and id(b) are different:
#    'a' and 'b' are two distinct Python ndarray wrapper objects, each with its own metadata.
#
# 2. Why ctypes.data can be different even though memory is shared:
#    In a sliced view (e.g., a[2:]), the view starts at an offset index, so its pointer
#    points to (start_address + offset * itemsize).
#
# 3. Why a.base is None:
#    'a' owns its allocated memory buffer and is not derived from any other array.
#
# 4. Why b.base points to a:
#    'b' is a view referencing 'a' as its data source.
#
# 5. Which object owns the memory:
#    Array 'a' owns the underlying memory buffer.

## Q15. Final Comparison

Create the following comparison table based on your observations.

Feature, Normal Indexing, Fancy Indexing, Boolean Indexing, View, Copy,
Purpose

Returns Single Element / Multiple Elements






Shares Memory










Creates New ndarray Object










Changes Affect Original










Typical Use Case











Finally, write 8–10 lines explaining:
- What you learned about indexing and slicing.
- The difference between Normal Indexing, Fancy Indexing, and Boolean Indexing.
- The difference between View and Copy.
- When you would use each in real-world Data Science projects.



In [19]:
import pandas as pd

# Comparison Table Data
data = {
    "Feature": [
        "Purpose",
        "Returns",
        "Shares Memory",
        "Creates New ndarray Object",
        "Changes Affect Original",
        "Typical Use Case"
    ],
    "Normal Indexing": [
        "Access continuous elements/slices",
        "Single element or ndarray",
        "Yes (for slicing) / No (scalar)",
        "Yes (for slicing)",
        "Yes (for slicing)",
        "Extracting sub-matrices, row/column ranges"
    ],
    "Fancy Indexing": [
        "Access non-contiguous elements via index arrays",
        "Multiple elements (ndarray)",
        "No",
        "Yes",
        "No",
        "Arbitrary coordinate lookups, batch extraction"
    ],
    "Boolean Indexing": [
        "Filter elements using logical condition masks",
        "Multiple elements (1D ndarray)",
        "No",
        "Yes",
        "No",
        "Outlier filtering, thresholding, data cleaning"
    ],
    "View": [
        "Access array data via alternate stride/offset",
        "Multiple elements (ndarray)",
        "Yes",
        "Yes",
        "Yes",
        "Memory-efficient subset processing"
    ],
    "Copy": [
        "Create an independent duplicate in memory",
        "Multiple elements (ndarray)",
        "No",
        "Yes",
        "No",
        "Isolating data preprocessing safely"
    ]
}

df_comparison = pd.DataFrame(data)
print(df_comparison.to_string(index=False))

                   Feature                            Normal Indexing                                  Fancy Indexing                               Boolean Indexing                                          View                                      Copy
                   Purpose          Access continuous elements/slices Access non-contiguous elements via index arrays  Filter elements using logical condition masks Access array data via alternate stride/offset Create an independent duplicate in memory
                   Returns                  Single element or ndarray                     Multiple elements (ndarray)                 Multiple elements (1D ndarray)                   Multiple elements (ndarray)               Multiple elements (ndarray)
             Shares Memory            Yes (for slicing) / No (scalar)                                              No                                             No                                           Yes                               

**Normal Indexing**

* **Purpose:** Access continuous elements or slices.


* **Returns:** Single element or `ndarray` (slice).


* **Shares Memory:** Yes (for slicing) / No (for a single scalar element).


* **Creates New ndarray:** Yes (for slicing).


* **Changes Affect Original:** Yes (for slicing).


* **Typical Use Case:** Extracting sub-matrices and row/column ranges.



**Fancy Indexing**

* **Purpose:** Access non-contiguous elements via index arrays or lists.


* **Returns:** Multiple elements (`ndarray`).


* **Shares Memory:** No.


* **Creates New ndarray:** Yes.


* **Changes Affect Original:** No.


* **Typical Use Case:** Extracting specific arbitrary coordinate pairs and batch lookups.



**Boolean Indexing**

* **Purpose:** Filter elements using logical condition masks.


* **Returns:** Multiple elements (1D `ndarray`).


* **Shares Memory:** No.


* **Creates New ndarray:** Yes.


* **Changes Affect Original:** No.


* **Typical Use Case:** Filtering outliers, thresholding, and conditional data cleaning.



**View**

* **Purpose:** Access array data with an alternate layout, stride, or offset.


* **Returns:** Multiple elements (`ndarray`).


* **Shares Memory:** Yes.


* **Creates New ndarray:** Yes.


* **Changes Affect Original:** Yes.


* **Typical Use Case:** Memory-efficient subset processing and heavy matrix manipulation.



**Copy**

* **Purpose:** Create an independent duplicate in memory.


* **Returns:** Multiple elements (`ndarray`).


* **Shares Memory:** No.


* **Creates New ndarray:** Yes.


* **Changes Affect Original:** No.


* **Typical Use Case:** Isolating data transformations and feature engineering safely without mutating raw data.