# NumPy Questions

## I. Array Creation by Dimension

1. Create a single-element NumPy array containing the value 42.


In [42]:
import numpy as np

arr = np.array(42)
print(arr)

42


2. Create a one-dimensional array containing the numbers 10, 20, 30, 40, and 50.

In [43]:
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


3. Create a two-dimensional array that forms a 3×3 matrix with numbers from 1 to 9.


In [44]:
arr = np.arange(1, 10).reshape(3, 3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


4. Create a three-dimensional array with shape (2, 2, 3) containing numbers from 1 to 12.


In [45]:
arr = np.arange(1, 13).reshape(2, 2, 3)
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


5. Determine how many dimensions a given array has.

In [47]:
arr = np.arange(1, 13).reshape(2, 2, 3)
print(arr.ndim)

3


## II. Array Creation Methods

6. Create a 3×3 matrix where all diagonal elements are 1 and the rest are 0.




In [48]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


7. Create a 2×3 matrix filled entirely with zeros, another 2×3 matrix filled with ones, and a 2×3 matrix with uninitialized values [ empty ] .


In [49]:
zeros_mat = np.zeros((2, 3))
ones_mat = np.ones((2, 3))
empty_mat = np.empty((2, 3))

print("Zeros:\n", zeros_mat)
print("Ones:\n", ones_mat)
print("Empty:\n", empty_mat)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Empty:
 [[8.99055445e-316 0.00000000e+000 6.86342166e-310]
 [6.86342166e-310 6.86342166e-310 5.78243365e-317]]


8. Create a 3×3 matrix where every element has the value 9.

In [50]:
arr = np.full((3, 3), 9)
print(arr)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


9. Transform a one-dimensional array of 8 elements into a three-dimensional array with shape (2, 2, 2).


In [51]:
arr = np.arange(8).reshape(2, 2, 2)
print(arr)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


##III. Linspace & Arange Concepts

10. Create a one-dimensional array of 5 numbers that are evenly spaced between 0 and 10, including both endpoints.

In [52]:
arr = np.linspace(0, 10, 5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


11. Create a sequence of numbers starting at 0 and ending before 1, with a difference of 0.1 between consecutive numbers. Explain any floating-point issues you notice.


In [53]:
arr = np.arange(0, 1, 0.1)
print(arr)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


12. Create an array of integers starting from 5 up to 20, with each number increasing by 3.

In [54]:
arr = np.arange(5, 20, 3)
print(arr)

[ 5  8 11 14 17]


13. Create 6 numbers evenly spaced between 5 and 10, but do not include the endpoint value (10).

In [55]:
arr = np.linspace(5, 10, 6, endpoint=False)
print(arr)

[5.         5.83333333 6.66666667 7.5        8.33333333 9.16666667]


14. Use np.info() on a 2D array and explore what information it provides.

In [56]:
arr = np.array([[1, 2], [3, 4]])
np.info(arr)

class:  ndarray
shape:  (2, 2)
strides:  (16, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0xadae590
byteorder:  little
byteswap:  False
type: int64


##IV. Random Number Generation

15. Create an array of 5 random whole numbers ranging from 0 to 9.

In [57]:
arr = np.random.randint(0, 10, size=5)
print(arr)

[7 4 4 5 5]


16. Create a 2×3 array of random whole numbers ranging from 50 to 100.

In [58]:
arr = np.random.randint(50, 101, size=(2, 3))
print(arr)

[[70 96 86]
 [64 76 55]]


17. You have an array of test scores: [2, 8, 12, 18, 25]. Some scores are too low and some are too high. Modify the array so that all scores less than 5 become 5, and all scores greater than 15 become 15.

In [59]:
scores = np.array([2, 8, 12, 18, 25])
modified_scores = np.clip(scores, 5, 15)
print(modified_scores)

[ 5  8 12 15 15]


##V. Array Attributes: Shape, Size, Memory

22. Find the shape, total number of elements, and number of dimensions of an array.

In [60]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimensions:", arr.ndim)

Shape: (2, 3)
Size: 6
Dimensions: 2


23. For the array [[1,2,3],[4,5,6]], find its shape.


In [61]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

(2, 3)


24. Determine how many bytes each element of an array uses.

In [62]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.itemsize)

8


25. Explain how total memory used by an array relates to the element size and number of elements.

In [63]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Total memory using nbytes:", arr.nbytes)
print("Calculated (size * itemsize):", arr.size * arr.itemsize)

Total memory using nbytes: 48
Calculated (size * itemsize): 48


26. For an array of three 32-bit integers, calculate the total memory in bytes.

In [64]:
arr = np.array([1, 2, 3], dtype=np.int32)
print("Total bytes:", arr.nbytes)

Total bytes: 12


27. For a 3×3 array of 64-bit floating-point numbers, calculate its memory usage in bytes.

In [65]:
arr = np.zeros((3, 3), dtype=np.float64)
print("Total bytes:", arr.nbytes)

Total bytes: 72


##VI. List vs Array

28. Explain the differences between Python lists and NumPy arrays in terms of memory, operations, and performance.

Memory: Python lists store pointers referencing scattered objects across memory; NumPy arrays store homogeneous data in single contiguous memory buffers.

Operations: Python lists concatenate on + and repeat on *; NumPy arrays perform vectorized, element-wise math directly.

Performance: NumPy operations run in optimized C routines with SIMD vectorization, executing significantly faster than Python for loops.

29. Multiply a Python list and a NumPy array by 2. Compare the results.

In [66]:
py_list = [1, 2, 3]
np_arr = np.array([1, 2, 3])

print("List * 2:", py_list * 2)
print("Array * 2:", np_arr * 2)

List * 2: [1, 2, 3, 1, 2, 3]
Array * 2: [2 4 6]


30. Add two Python lists and then add two NumPy arrays of the same numbers. Compare the results.

In [67]:
l1, l2 = [1, 2], [3, 4]
a1, a2 = np.array([1, 2]), np.array([3, 4])

print("List + List:", l1 + l2)
print("Array + Array:", a1 + a2)

List + List: [1, 2, 3, 4]
Array + Array: [4 6]


31. Convert a Python list [10, 20, 30, 40] into a NumPy array and multiply each element by 2.

In [68]:
py_list = [10, 20, 30, 40]
arr = np.array(py_list) * 2
print(arr)

[20 40 60 80]


32. Explain why NumPy arrays are stored in contiguous blocks of memory and why this is important.

Explanation: Contiguous allocation stores elements in continuous adjacent memory slots. This allows CPU pre-fetchers to leverage CPU cache locality (reducing cache misses) and enables SIMD hardware vectorization to process multiple elements in a single clock cycle.

##VII. Indexing & Slicing

33. From a 1D array [10, 20, 30, 40, 50], extract the 2nd and 4th elements.

In [69]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[[1, 3]])

[20 40]


34. From a 2D array, access the element in the first row and second column.

In [70]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
print(arr[0, 1])

20


35. Explain the difference between selecting elements by index and selecting elements by a condition (boolean indexing).

Positional Indexing: Retrieves elements using explicit zero-based integer index locations (e.g., arr[0]).

Boolean Indexing: Uses a boolean condition array (mask) of True/False values to filter and return only elements where the condition is True (e.g., arr[arr > 5]).

36. From an array [3, 7, 2, 9, 5, 10], select only the elements that are greater than 5.

In [71]:
arr = np.array([3, 7, 2, 9, 5, 10])
print(arr[arr > 5])

[ 7  9 10]


37. From [10, 20, 30, 40, 50, 60], select every other element starting from the first.


In [72]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[::2])

[10 30 50]


38. Replace all negative numbers in [1, -2, 3, -4, 5] with zero.


In [73]:
arr = np.array([1, -2, 3, -4, 5])
arr[arr < 0] = 0
print(arr)

[1 0 3 0 5]


39. Explain whether creating a sub-array using slicing creates a view of the original array or a copy.

In [74]:
original = np.array([1, 2, 3, 4])
sub_arr = original[1:3]
sub_arr[0] = 99

print("Original array:", original)
print("Shares memory:", sub_arr.base is original)

Original array: [ 1 99  3  4]
Shares memory: True


##VIII. Data Types and Numeric Precision

40. Explain the differences between 8-bit, 16-bit, and 32-bit integers.

int8: 1 byte, range -128 to 127.

int16: 2 bytes, range -32,768 to 32,767.

int32: 4 bytes, range -2,147,483,648 to 2,147,483,647.

41. Explain the differences between 16-bit and 64-bit floating-point numbers.

float16 (Half Precision): 5 exponent bits, 10 mantissa bits (~3–4 decimal digits of precision).

float64 (Double Precision): 11 exponent bits, 52 mantissa bits (~15–17 decimal digits of precision).

42. Create an array of 5 floating-point numbers stored with 32-bit precision.

In [75]:
arr = np.array([1.0, 2.0, 3.0, 4.0, 5.0], dtype=np.float32)
print(arr, arr.dtype)

[1. 2. 3. 4. 5.] float32


43. Divide two arrays of 8-bit integers. What data type do you get in the result?

In [76]:
a = np.array([10, 20], dtype=np.int8)
b = np.array([2, 5], dtype=np.int8)
res = a / b
print("Result:", res)
print("Result dtype:", res.dtype)

Result: [5. 4.]
Result dtype: float64


44. What is the most suitable data type for storing RGB pixel values (0–255)?

In [77]:
pixel = np.array([255, 128, 0], dtype=np.uint8)
print(pixel.dtype)

uint8


45. Convert an array of integers to floating-point numbers.

In [78]:
int_arr = np.array([1, 2, 3])
float_arr = int_arr.astype(np.float64)
print(float_arr, float_arr.dtype)

[1. 2. 3.] float64


46. Convert a 32-bit floating-point array [1.5, 2.5, 3.5] to 16-bit integers and describe what happens.

In [79]:
arr = np.array([1.5, 2.5, 3.5], dtype=np.float32)
converted = arr.astype(np.int16)
print(converted, converted.dtype)

[1 2 3] int16


47. Assign a floating-point number to an integer array element. Describe the result.

In [80]:
arr = np.array([10, 20, 30], dtype=np.int32)
arr[0] = 45.89
print(arr)

[45 20 30]


##IX. Mixed Data Type & Casting Scenarios

48. Create an array containing [1, 2.5, True, '3'] and describe what data type the array elements become.

In [81]:
arr = np.array([1, 2.5, True, '3'])
print(arr)
print("Data type:", arr.dtype)

['1' '2.5' 'True' '3']
Data type: <U32


49. If an array contains both integers and floating-point numbers, what data type is assigned?

In [83]:
arr = np.array([1, 2.5, 3])
print("Array:", arr)
print("Data type:", arr.dtype)

Array: [1.  2.5 3. ]
Data type: float64


50. Why is 64-bit floating-point preferred for calculations over 16-bit floating-point?


Precision & Dynamic Range: float64 offers ~15–17 decimal digits of precision with an 11-bit exponent, whereas float16 offers only ~3–4 decimal digits with a 5-bit exponent.

Numerical Stability: In iterative or large-scale mathematical computations, float16 quickly leads to underflow, overflow, and accumulated rounding errors.

Hardware Support: Standard CPUs compute 64-bit floating-point math natively in registers with minimal overhead.

51. Convert [1, 0, 3, 0, 5] into a boolean array and describe the output.


In [86]:
arr = np.array([1, 0, 3, 0, 5])
bool_arr = arr.astype(bool)

print("Boolean Array:", bool_arr)
print("Data type:", bool_arr.dtype)

Boolean Array: [ True False  True False  True]
Data type: bool


52. Explain the role of specifying the data type when creating an array.

Memory Optimization: Choosing smaller data types (e.g., np.uint8 for images or np.int16 vs np.int64) significantly reduces RAM usage.  

Preventing Data Loss & Overflow: Explicit typing prevents accidental type promotion and ensures hardware compatibility (e.g., matching GPU tensor expectations).

Performance: Smaller bitwidths maximize cache locality and increase vectorization efficiency (SIMD).

##X. Exploring Documentation

53. Explore the NumPy documentation and learn about all the array methods and functions that we have studied in class so far. Write a short note on what each method does and how it can be used.

**Array Creation Functions**

* **`np.array(object, dtype=None)`**: Converts Python sequences (like lists or tuples) into an N-dimensional NumPy array (`ndarray`) with an optional specified data type.


* **`np.zeros(shape, dtype=float)`**: Creates and returns a new array of the given shape, with every element initialized to zero (`0`).


* **`np.ones(shape, dtype=float)`**: Returns a new array of the specified shape and type, filled entirely with ones (`1`).


* **`np.empty(shape, dtype=float)`**: Allocates an array of the given shape without initializing its entries, which returns whatever uninitialized values happen to exist in that memory block.


* **`np.full(shape, fill_value, dtype=None)`**: Generates an array of a specified shape where every element is filled with a constant scalar value (`fill_value`).


* **`np.eye(N, M=None, k=0)`**: Creates a 2D matrix with ones along the $k$-th diagonal and zeros elsewhere.


* **`np.identity(n)`**: Produces an $n \times n$ square identity matrix with ones on the main diagonal and zeros elsewhere.


* **`np.zeros_like(a)` / `np.ones_like(a)` / `np.empty_like(a)**`: Creates a new array of zeros, ones, or uninitialized values that mirrors the shape and data type of the input array `a`.


* **`np.tril(m, k=0)` / `np.triu(m, k=0)**`: Returns the lower or upper triangular part of an array, zeroing out elements above or below the $k$-th diagonal.



**Sequencing & Range Functions**

* **`np.arange([start,] stop[, step,], dtype=None)`**: Generates evenly spaced numerical values within a half-open interval $[start, stop)$ using a defined step size.


* **`np.linspace(start, stop, num=50, endpoint=True)`**: Returns a specified count (`num`) of evenly spaced numbers over a closed or half-open interval $[start, stop]$.



**Array Inspection Attributes**

* **`.ndim`**: Displays the number of dimensions/axes of an array.


* **`.shape`**: Returns a tuple of integers showing the size of the array along each dimension.


* **`.size`**: Returns the total number of elements contained in the array.


* **`.dtype`**: Specifies the data type of the array elements (e.g., `int8`, `int64`, `float64`).


* **`.itemsize`**: Returns the memory footprint of a single element in bytes.


* **`.nbytes`**: Returns the total number of bytes consumed by the array data ($\text{size} \times \text{itemsize}$).


* **`.base`**: Identifies whether the array owns its own memory buffer or is a view referencing another base array.


* **`.ctypes.data`**: Provides the exact physical memory address pointer for the array's contiguous data buffer.



**Array Reshaping & Manipulation Methods**

* **`.reshape(shape, order='C')`**: Reconfigures the dimensions of an array without altering its underlying data, returning a view when possible.


* **`np.resize(a, new_shape)`**: Returns a new array with the specified shape, repeating copies of `a` if the new shape is larger.


* **`.astype(dtype)`**: Copies and casts the elements of an array to a newly specified data type.


* **`np.clip(a, a_min, a_max)`**: Restricts the values of an array to remain within the interval $[a\_min, a\_max]$.


* **`np.insert(arr, obj, values, axis=None)`**: Inserts values along a chosen axis before the given indices, returning a new copy.


* **`np.delete(arr, obj, axis=None)`**: Returns a new array with sub-arrays along the specified axis removed.


* **`.copy()`**: Creates a completely independent deep copy of the array in a newly allocated memory block.


* **`.view()`**: Creates a new array object that shares and references the exact same memory buffer as the original array.



**Random Number Generation Functions**

* **`np.random.randint(low, high=None, size=None)`**: Generates random whole numbers from the discrete uniform distribution over the range $[low, high)$.


* **`np.random.rand(d0, d1, ...)` / `np.random.random(size)**`: Generates random floating-point values from a uniform distribution over $[0.0, 1.0)$.


* **`np.random.uniform(low=0.0, high=1.0, size=None)`**: Samples random numbers from a defined continuous uniform distribution $[low, high)$.


* **`np.random.randn(d0, d1, ...)`**: Generates random floating-point numbers sampled from the standard normal (Gaussian) distribution ($\mu=0, \sigma=1$).


* **`np.random.normal(loc=0.0, scale=1.0, size=None)`**: Samples numbers from a normal distribution with a customized mean (`loc`) and standard deviation (`scale`).


* **`np.random.seed(seed)`**: Sets the random seed generator to ensure reproducible random outputs across runs.



**Statistical & Aggregate Functions**

* **`np.min(a)` / `.min()` & `np.max(a)` / `.max()**`: Calculates the minimum or maximum value across an array or along a designated axis.


* **`np.argmin(a)` / `np.argmax(a)**`: Returns the index position of the minimum or maximum element.


* **`np.mean(a)` / `.mean()**`: Computes the arithmetic mean of an array or along a specified axis.


* **`np.median(a)`**: Computes the median value along a specified axis.


* **`np.std(a)` / `.std()` & `np.var(a)` / `.var()**`: Calculates the standard deviation and variance across the array or along a given axis.


* **`np.percentile(a, q)` / `np.quantile(a, q)**`: Computes the $q$-th percentile or quantile of the data along the specified axis.


* **`np.nanmean(a)`, `np.nanmin(a)`, `np.nanmax(a)`, `np.nanstd(a)`, `np.nanvar(a)**`: Computes respective statistics while safely ignoring any `NaN` (Not a Number) values present in the array.



**Diagnostic Tool**

* **`np.info(object)`**: Outputs detailed internal diagnostic information about an array, including its class, shape, strides, data type, and memory contiguity.