#📌 NumPy Task

##Indexing, Slicing, Fancy Indexing, Boolean Logic & Broadcasting

##🔹 Part A: Integer Indexing & Slicing


1️⃣ Integer Indexing & Negative Indexing

Input

A = np.array([100, 200, 300, 400, 500])

Expected Output

First two elements      → [100, 200]

Last three elements     → [300, 400, 500]

Middle element          → 300

Task

 Extract the above elements using integer indexing and negative indexing.


In [2]:
import numpy as np

A = np.array([100, 200, 300, 400, 500])

first_two = A[:2]
last_three = A[-3:]
middle = A[2]

print("First two elements:", first_two)
print("Last three elements:", last_three)
print("Middle element:", middle)

First two elements: [100 200]
Last three elements: [300 400 500]
Middle element: 300


2️⃣ Slicing (Exclude First & Last)

Input

A = np.array([2, 4, 6, 8, 10, 12, 14])

Expected Output

[4, 6, 8, 10, 12]

Task

 Extract all elements except the first and last using slicing.


In [3]:
A = np.array([2, 4, 6, 8, 10, 12, 14])
result = A[1:-1]

print(result)

[ 4  6  8 10 12]


3️⃣ 2D Array Indexing & Slicing

Input

M = np.array([

    [10, 20, 30, 40],

    [50, 60, 70, 80],

    [90, 100, 110, 120]

])

Expected Output

Sub-matrix        → [[20, 30],

                     [60, 70]]

Last row          → [90, 100, 110, 120]

First column      → [10, 50, 90]

Task

 Use row–column slicing to obtain the above outputs.


In [4]:
M = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

sub_matrix = M[0:2, 1:3]
last_row = M[-1, :]
first_col = M[:, 0]

print("Sub-matrix:\n", sub_matrix)
print("Last row:", last_row)
print("First column:", first_col)

Sub-matrix:
 [[20 30]
 [60 70]]
Last row: [ 90 100 110 120]
First column: [10 50 90]


4️⃣ Step Slicing

Input

A = np.array([1, 2, 3, 4, 5, 6, 7, 8])

Expected Output

[1, 4, 7]

Task

 Extract every third element starting from index 0.


In [5]:
A = np.array([1, 2, 3, 4, 5, 6, 7, 8])
result = A[0::3]

print(result)

[1 4 7]


##🔹 Part B: Boolean Indexing

5️⃣ Condition-Based Filtering

Input

A = np.array([5, 12, 17, 3, 8, 20])

Expected Output

Values > 10        → [12, 17, 20]

Values ≤ 8         → [5, 3, 8]

Task

 Use boolean indexing to extract both outputs.


In [7]:
A = np.array([5, 12, 17, 3, 8, 20])

greater_10 = A[A > 10]
less_equal_8 = A[A <= 8]

print("Values > 10:", greater_10)
print("Values ≤ 8:", less_equal_8)

Values > 10: [12 17 20]
Values ≤ 8: [5 3 8]


6️⃣ Multiple Boolean Conditions

Input

A = np.array([10, 15, 20, 25, 30, 35])

Expected Output

[20, 25, 30, 35]

Task

 Extract values that are greater than 15 AND divisible by 5.


In [8]:
A = np.array([10, 15, 20, 25, 30, 35])
result = A[(A > 15) & (A % 5 == 0)]

print(result)

[20 25 30 35]


7️⃣ Boolean Filtering + Counting

Input

A = np.array([3, -2, 0, 5, -7, 8])

Expected Output

Non-negative values → [3, 0, 5, 8]

Negative count      → 2

Task

 Use boolean indexing to filter and count.


In [10]:
A = np.array([3, -2, 0, 5, -7, 8])

non_negative = A[A >= 0]
negative_count = np.sum(A < 0)

print("Non-negative values:", non_negative)
print("Negative count:", negative_count)

Non-negative values: [3 0 5 8]
Negative count: 2


8️⃣ Boolean Replacement

Input

A = np.array([1, 2, 3, 4, 5, 6, 7])

Expected Output

[-1, 2, -1, 4, -1, 6, -1]

Task

 Replace all odd numbers with -1 using boolean indexing.


In [11]:
A = np.array([1, 2, 3, 4, 5, 6, 7])
A[A % 2 != 0] = -1

print(A)

[-1  2 -1  4 -1  6 -1]


##🔹 Part C: Fancy Indexing

9️⃣ Index List Selection

Input

A = np.array([11, 22, 33, 44, 55, 66])

Expected Output

[22, 44, 66]

Task

 Extract elements at indices [1, 3, 5] using fancy indexing.


In [12]:
A = np.array([11, 22, 33, 44, 55, 66])
result = A[[1, 3, 5]]

print(result)

[22 44 66]


🔟 Rearranging Elements

Input

A = np.array([100, 200, 300, 400, 500])

Expected Output

[500, 300, 100]

Task

 Rearrange the array using fancy indexing only.


In [13]:
A = np.array([100, 200, 300, 400, 500])
result = A[[4, 2, 0]]

print(result)

[500 300 100]


1️⃣1️⃣ Fancy Indexing on 2D Array

Input

M = np.array([

    [1, 2, 3],

    [4, 5, 6],

    [7, 8, 9]

])

Expected Output

[1, 5, 9]

Task

 Extract diagonal elements using fancy indexing.


In [14]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

diagonal = M[[0, 1, 2], [0, 1, 2]]

print(diagonal)

[1 5 9]


1️⃣2️⃣ Row Reordering

Input

M = same as above

Expected Output

[[7, 8, 9],

 [1, 2, 3]]

Task

 Extract rows in the order row 2, then row 0.


In [15]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

reordered_rows = M[[2, 0]]

print(reordered_rows)

[[7 8 9]
 [1 2 3]]


##🔹 Part D: Boolean Indexing vs np.where()


1️⃣3️⃣ Filtering vs Transforming

Input

A = np.array([4, 9, 2, 7, 12, 3])

Expected Output

Boolean indexing → [9, 7, 12]

np.where         → [0, 1, 0, 1, 1, 0]

Task

Filter values > 5 using boolean indexing

Transform array using np.where()

In [16]:
A = np.array([4, 9, 2, 7, 12, 3])

filtered = A[A > 5]
transformed = np.where(A > 5, 1, 0)

print("Boolean indexing:", filtered)
print("np.where:", transformed)

Boolean indexing: [ 9  7 12]
np.where: [0 1 0 1 1 0]


1️⃣4️⃣ Replace Negatives (Two Methods)

Input

A = np.array([-5, 10, -3, 8, -1])

Expected Output

[0, 10, 0, 8, 0]

Task

 Replace negatives using:

- Boolean indexing

- np.where()
  
  Compare both approaches.



In [18]:
A1 = np.array([-5, 10, -3, 8, -1])
A2 = np.array([-5, 10, -3, 8, -1])

A1[A1 < 0] = 0
res_where = np.where(A2 < 0, 0, A2)

print("Boolean indexing:", A1)
print("np.where():", res_where)

Boolean indexing: [ 0 10  0  8  0]
np.where(): [ 0 10  0  8  0]


1️⃣5️⃣ Labeling Data with np.where()

Input

scores = np.array([45, 60, 30, 85, 90])

Expected Output

Filtered scores → [60, 85, 90]

Labels          → ["Fail", "Pass", "Fail", "Pass", "Pass"]

Task

Filter using boolean indexing


Label using np.where()



In [19]:
scores = np.array([45, 60, 30, 85, 90])

filtered = scores[scores >= 50]
labels = np.where(scores >= 50, "Pass", "Fail")

print("Filtered scores:", filtered)
print("Labels:", labels.tolist())

Filtered scores: [60 85 90]
Labels: ['Fail', 'Pass', 'Fail', 'Pass', 'Pass']


##🔹 Part E: Broadcasting

1️⃣6️⃣ Row-wise Broadcasting

Input

M = np.array([[1, 2, 3],

              [4, 5, 6]])

A = np.array([10, 20, 30])

Expected Output

Addition     → [[11, 22, 33],

                [14, 25, 36]]

Subtraction  → [[-9, -18, -27],

                [-6, -15, -24]]

Task

 Perform both operations using broadcasting.


In [20]:
M = np.array([[1, 2, 3],
              [4, 5, 6]])
A = np.array([10, 20, 30])

add_res = M + A
sub_res = M - A

print("Addition:\n", add_res)
print("Subtraction:\n", sub_res)

Addition:
 [[11 22 33]
 [14 25 36]]
Subtraction:
 [[ -9 -18 -27]
 [ -6 -15 -24]]


1️⃣7️⃣ Row Normalization

Input

M = np.array([[2, 4],

              [6, 8]])

Expected Output

[[1, 2],

 [3, 4]]

Task

 Divide each row by [2, 2] using broadcasting.


In [21]:
M = np.array([[2, 4],
              [6, 8]])
divisor = np.array([2, 2])

result = (M // divisor)

print(result)

[[1 2]
 [3 4]]


1️⃣8️⃣ Scalar Broadcasting

Input

A = np.array([10, 20, 30])

Expected Output

[15, 25, 35]

Task

 Add scalar 5 using broadcasting.


In [22]:
A = np.array([10, 20, 30])
result = A + 5

print(result)

[15 25 35]


1️⃣9️⃣ Boolean vs np.where() on 2D

Input

M = np.array([[5, 10, 15],

              [20, 25, 30]])

Expected Output

[[5, 10, 15],

 [20, 20, 20]]

Task

 Set values > 20 to 20 using:

Boolean indexing

np.where()

In [23]:
M1 = np.array([[5, 10, 15],
               [20, 25, 30]])
M2 = np.array([[5, 10, 15],
               [20, 25, 30]])

M1[M1 > 20] = 20
res_where = np.where(M2 > 20, 20, M2)

print("Boolean indexing:\n", M1)
print("np.where():\n", res_where)

Boolean indexing:
 [[ 5 10 15]
 [20 20 20]]
np.where():
 [[ 5 10 15]
 [20 20 20]]


2️⃣0️⃣ Broadcasting Concept Check

Input

M = np.array([[1, 2],

              [3, 4],

              [5, 6]])

A = np.array([10, 20])

Expected Output

[[11, 22],

 [13, 24],

 [15, 26]]

Task

 Add A to each row and explain why broadcasting works here.


In [24]:
M = np.array([[1, 2],
              [3, 4],
              [5, 6]])
A = np.array([10, 20])

result = M + A
print(result)

[[11 22]
 [13 24]
 [15 26]]
