#Array_Creation_numpy

##SECTION 1 — Basic NumPy Array Creation

Question 1

Problem Description

Create a NumPy array using the following numbers.

Input

[5, 10, 15, 20]

Task

Create a NumPy array from the given list.

Expected Output Format

1-dimensional NumPy array.


In [1]:
import numpy as np

In [2]:
arr1 = np.array([5, 10, 15, 20])
print(arr1)

[ 5 10 15 20]


Question 2

Problem Description

Create a NumPy array containing floating point values.

Input

[1.5, 2.5, 3.5, 4.5]

Task

Convert the list into a NumPy array.

Expected Output Format

1D NumPy array containing float values.


In [3]:
arr2 = np.array([1.5, 2.5, 3.5, 4.5])
print(arr2)

[1.5 2.5 3.5 4.5]


##SECTION 2 — Creating Arrays from Python Data Structures


Question 3

Problem Description

You are given a Python list containing numerical values. Convert this list into a NumPy array.

Input

[10, 20, 30, 40, 50]

Task

Create a NumPy array using the appropriate NumPy function.

Expected Output Format

1D NumPy array containing the same values.


In [4]:
lst = [10, 20, 30, 40, 50]
arr3 = np.array(lst)
print(arr3)

[10 20 30 40 50]


Question 4

Problem Description

A Python tuple containing numbers is given. Convert this tuple into a NumPy array.

Input

(5, 10, 15, 20)

Task

Create a NumPy array from the tuple.

Expected Output Format

1D NumPy array.


In [5]:
tup = (5, 10, 15, 20)
arr4 = np.array(tup)
print(arr4)

[ 5 10 15 20]


Question 5

Problem Description

A Python set is provided. Convert the set into a NumPy array.

Input

{2, 4, 6, 8, 10}

Task

Create a NumPy array containing all elements.

Expected Output Format

NumPy array containing the values.


In [43]:
s = {2, 4, 6, 8, 10}
arr5 = np.array(sorted(s))
print(arr5)

[ 2  4  6  8 10]


Question 6

Problem Description

A dictionary contains key-value pairs. Extract the dictionary keys and convert them into a NumPy array.

Input

{

"A":10,

"B":20,

"C":30

}

Task

Create a NumPy array containing the dictionary keys.

Expected Output Format

Array containing keys.


In [7]:
d = {"A": 10, "B": 20, "C": 30}
keys_arr = np.array(list(d.keys()))
print(keys_arr)

['A' 'B' 'C']


Question 7

Problem Description

Using the same dictionary, convert the values into a NumPy array.

Input

{

"A":10,

"B":20,

"C":30

}

Task

Create a NumPy array containing the dictionary values.

Expected Output Format

Array containing values.


In [8]:
values_arr = np.array(list(d.values()))
print(values_arr)

[10 20 30]


##SECTION 3 — Creating Arrays Using NumPy Functions

Question 8

Problem Description

Create a NumPy array from the following list.

Input

[1, 2, 3, 4, 5]

Task

Use the NumPy function that converts Python objects into arrays.

Expected Output Format

1D NumPy array.


In [9]:
arr8 = np.asarray([1, 2, 3, 4, 5])
print(arr8)

[1 2 3 4 5]


Question 9

Problem Description

Create a NumPy matrix from a nested list.

Input

[

[10,20],

[30,40]

]

Task

Convert the nested list into a NumPy array.

Expected Output Format

2×2 matrix.

In [10]:
nested_list = [[10, 20], [30, 40]]
matrix9 = np.array(nested_list)
print(matrix9)

[[10 20]
 [30 40]]


Question 10

Problem Description

Generate sequential numbers using NumPy.

Task

Use np.arange() to create numbers starting from 1 up to 10.

Expected Output Format

Array containing numbers from 1 to 9.


In [11]:
arr10 = np.arange(1, 10)
print(arr10)

[1 2 3 4 5 6 7 8 9]


Question 11

Problem Description

Generate numbers with a specific step size.

Task

Use np.arange() to generate numbers from 0 to 20 with step size 2.

Expected Output Format

Array containing even numbers.


In [12]:
arr11 = np.arange(0, 21, 2)
print(arr11)

[ 0  2  4  6  8 10 12 14 16 18 20]


Question 12

Problem Description

Generate numbers starting from 5 up to 50 with step size 5.

Task

Use np.arange().

Expected Output Format

Array increasing by 5.


In [13]:
arr12 = np.arange(5, 51, 5)
print(arr12)

[ 5 10 15 20 25 30 35 40 45 50]


##SECTION 4 — Creating Evenly Spaced Numbers

Question 13

Problem Description

Generate evenly spaced numbers between two values.

Task

Use np.linspace() to create 5 evenly spaced numbers between 0 and 10.

Expected Output Format

Array containing 5 numbers.


In [14]:
arr13 = np.linspace(0, 10, 5)
print(arr13)

[ 0.   2.5  5.   7.5 10. ]


Question 14

Problem Description

Generate evenly spaced numbers between 1 and 100.

Task

Use np.linspace() to create 10 numbers.

Expected Output Format

Array containing 10 numbers.


In [15]:
arr14 = np.linspace(1, 100, 10)
print(arr14)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


Question 15

Problem Description

Generate evenly spaced numbers between -1 and 1.

Task

Use np.linspace() to create 8 numbers.

Expected Output Format

Array containing 8 values.


In [16]:
arr15 = np.linspace(-1, 1, 8)
print(arr15)

[-1.         -0.71428571 -0.42857143 -0.14285714  0.14285714  0.42857143
  0.71428571  1.        ]


##SECTION 5 — Arrays Filled with Specific Values

Question 16

Problem Description

Create an array filled with zeros.

Task

Use NumPy to create an array of five zeros.

Expected Output Format

Array containing zeros.


In [17]:
zeros_arr = np.zeros(5)
print(zeros_arr)

[0. 0. 0. 0. 0.]


Question 17

Problem Description

Create a 2 × 3 matrix filled with zeros.

Task

Use NumPy function.

Expected Output Format

2×3 zero matrix.


In [18]:
zeros_mat = np.zeros((2, 3))
print(zeros_mat)

[[0. 0. 0.]
 [0. 0. 0.]]


Question 18

Problem Description

Create an array filled with ones.

Task

Generate an array containing six ones.

Expected Output Format

Array containing ones.


In [42]:
ones_arr = np.ones(6)
print(ones_arr)

[1. 1. 1. 1. 1. 1.]


Question 19

Problem Description

Create a 3 × 3 matrix filled with ones.

Task

Use NumPy function.

Expected Output Format

3×3 matrix of ones.


In [20]:
ones_mat = np.ones((3, 3))
print(ones_mat)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Question 20

Problem Description

Create a constant matrix.

Task

Use np.full() to generate a 3 × 3 matrix filled with value 7.

Expected Output Format

Matrix containing only 7.


In [21]:
full_mat7 = np.full((3, 3), 7)
print(full_mat7)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


Question 21

Problem Description

Create a 4 × 4 matrix filled with value 100.

Task

Use appropriate NumPy function.

Expected Output Format

4×4 constant matrix.


In [22]:
full_mat100 = np.full((4, 4), 100)
print(full_mat100)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]


Question 22

Problem Description

Create an empty NumPy array.

Task

Use np.empty() to create an array of size 4.

Expected Output Format

Array with 4 elements (values may be random).


In [23]:
empty_arr = np.empty(4)
print(empty_arr)

[ 2.5  5.   7.5 10. ]


Question 23

Problem Description

Create a 3 × 3 empty matrix.

Task

Use NumPy function.

Expected Output Format

3×3 empty matrix.


In [24]:
empty_mat = np.empty((3, 3))
print(empty_mat)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


##SECTION 6 — Identity and Diagonal Matrices

Question 24

Problem Description

Create an identity matrix.

Task

Use np.eye() to generate a 3 × 3 identity matrix.

Expected Output Format

Matrix with diagonal values equal to 1.


In [25]:
eye_3 = np.eye(3)
print(eye_3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Question 25

Problem Description

Create a 5 × 5 identity matrix.

Task

Use np.eye().

Expected Output Format

5×5 identity matrix.


In [26]:
eye_5 = np.eye(5)
print(eye_5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Question 26

Problem Description

Create an identity matrix using another NumPy function.

Task

Use np.identity() to generate 4 × 4 matrix.

Expected Output Format

4×4 identity matrix.


In [27]:
id_4 = np.identity(4)
print(id_4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Question 27

Problem Description

Create a diagonal matrix.

Input

[5, 10, 15, 20]

Task

Use np.diag() to place numbers on diagonal.

Expected Output Format

Matrix with diagonal values.


In [28]:
diag_27 = np.diag([5, 10, 15, 20])
print(diag_27)

[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]


Question 28

Problem Description

Create a diagonal matrix using numbers:

Input

[1, 2, 3, 4, 5]

Task

Generate a diagonal matrix.

Expected Output Format

Diagonal matrix.


In [29]:
diag_28 = np.diag([1, 2, 3, 4, 5])
print(diag_28)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


##SECTION 7 — Understanding Array Dimensions

Question 29

Problem Description

Create a NumPy array containing numbers from 1 to 5.

Task

Verify whether the array is 1-dimensional.

Expected Output Format

Array structure showing a single dimension.


In [30]:
arr29 = np.arange(1, 6)
print("Array:", arr29)
print("Number of dimensions:", arr29.ndim)

Array: [1 2 3 4 5]
Number of dimensions: 1


Question 30

Problem Description

Create a 2D NumPy array using the following data.

Input

[

[1,2,3],

[4,5,6]

]

Task

Convert the data into a NumPy matrix.

Expected Output Format

2×3 matrix.


In [31]:
arr30 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr30)
print("Shape:", arr30.shape)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


Question 31

Problem Description

Create a 3D NumPy array using the following structure.

Input

[

[[1,2],[3,4]],

[[5,6],[7,8]]

]

Task

Create a 3-dimensional NumPy array.

Expected Output Format

3D array.


In [32]:
arr31 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr31)
print("Dimensions:", arr31.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimensions: 3


##SECTION 8 — NumPy Array Properties

Question 32

Problem Description

Create a NumPy array.

Input

[10, 20, 30, 40, 50]

Task

Find the number of dimensions using a NumPy property.

Expected Output Format

Single integer value.


In [33]:
arr32 = np.array([10, 20, 30, 40, 50])
print(arr32.ndim)

1


Question 33

Problem Description

Create the following NumPy matrix.

Input

[

[1,2,3],

[4,5,6]

]

Task

Find the shape of the array.

Expected Output Format

Tuple representing rows and columns.


In [34]:
arr33 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr33.shape)

(2, 3)


Question 34

Problem Description

Create a NumPy array containing numbers from 1 to 20.

Task

Find the total number of elements.

Expected Output Format

Single numeric value.


In [35]:
arr34 = np.arange(1, 21)
print(arr34.size)

20


Question 35

Problem Description

Create a NumPy array with floating numbers.

Input

[1.5, 2.5, 3.5, 4.5]

Task

Determine the data type of the array elements.

Expected Output Format

NumPy dtype.


In [36]:
arr35 = np.array([1.5, 2.5, 3.5, 4.5])
print(arr35.dtype)

float64


Question 36

Problem Description

Create the following NumPy array.

Input

[10, 20, 30, 40]

Task

Determine the size of each element in bytes.

Expected Output Format

Numeric value representing bytes.


In [37]:
arr36 = np.array([10, 20, 30, 40])
print(arr36.itemsize)

8


##SECTION 9 — Practical Dataset Tasks

Question 37

Problem Description

Create a matrix representing marks of 3 students in 4 subjects.

Task

Generate a 3 × 4 NumPy matrix.

Expected Output Format

Matrix representing dataset.


In [38]:
marks = np.array([
    [85, 90, 78, 92],
    [76, 88, 85, 80],
    [90, 95, 89, 94]
])
print(marks)

[[85 90 78 92]
 [76 88 85 80]
 [90 95 89 94]]


Question 38

Problem Description

Generate evenly spaced numbers used for plotting graphs.

Task

Use np.linspace() to create 10 numbers between 1 and 100.

Expected Output Format

Array containing 10 numbers.


In [39]:
plot_points = np.linspace(1, 100, 10)
print(plot_points)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


Question 39

Problem Description

Create a placeholder matrix where values will be filled later.

Task

Generate a 4 × 4 matrix filled with zeros.

Expected Output Format

4×4 zero matrix.


In [40]:
placeholder_zeros = np.zeros((4, 4))
print(placeholder_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Question 40

Problem Description

Create a constant matrix used for initialization.

Task

Generate a 5 × 5 matrix filled with value 9.

Expected Output Format

5×5 constant matrix.


In [41]:
init_matrix = np.full((5, 5), 9)
print(init_matrix)

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]
